# Generated by Django 5.2.2 on 2025-06-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_managers_remove_user_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="username"
            ),
        ),
    ]
